/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Solo_Artist;

import Model.DBconnection;
import Welcome.Welcome1;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

public class sUpdateProfile extends javax.swing.JFrame {

    /**
     * Creates new form sUpdateProfile
     */
    public sUpdateProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sFName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sLName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sUName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sCharge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sPNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sAge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sLocation = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cancel2 = new javax.swing.JButton();
        sSignin = new javax.swing.JButton();
        sPWD = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        sMale = new javax.swing.JRadioButton();
        sFemale = new javax.swing.JRadioButton();
        pop = new javax.swing.JCheckBox();
        rock = new javax.swing.JCheckBox();
        hiphop = new javax.swing.JCheckBox();
        classical = new javax.swing.JCheckBox();
        country = new javax.swing.JCheckBox();
        rb = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sBio = new javax.swing.JTextArea();
        other = new javax.swing.JCheckBox();
        textS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Profile");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");

        sFName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");

        sLName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name");

        sUName.setEditable(false);
        sUName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Charge per song $");

        sCharge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sChargeKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone Number");

        sPNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sPNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sPNoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        sEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age");

        sAge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Location");

        sLocation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Music Genre");

        cancel2.setBackground(new java.awt.Color(255, 0, 0));
        cancel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancel2.setForeground(new java.awt.Color(255, 255, 255));
        cancel2.setText("CANCEL");
        cancel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });

        sSignin.setBackground(new java.awt.Color(255, 0, 0));
        sSignin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sSignin.setForeground(new java.awt.Color(255, 255, 255));
        sSignin.setText("UPDATE");
        sSignin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSigninActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");

        sMale.setForeground(new java.awt.Color(255, 255, 255));
        sMale.setText("Male");

        sFemale.setForeground(new java.awt.Color(255, 255, 255));
        sFemale.setText("Female");

        pop.setForeground(new java.awt.Color(255, 255, 255));
        pop.setText("Pop");

        rock.setForeground(new java.awt.Color(255, 255, 255));
        rock.setText("Rock");

        hiphop.setForeground(new java.awt.Color(255, 255, 255));
        hiphop.setText("Hip-hop");

        classical.setForeground(new java.awt.Color(255, 255, 255));
        classical.setText("Classical");

        country.setForeground(new java.awt.Color(255, 255, 255));
        country.setText("Country ");

        rb.setForeground(new java.awt.Color(255, 255, 255));
        rb.setText("R&B");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bio");

        sBio.setColumns(20);
        sBio.setRows(5);
        jScrollPane2.setViewportView(sBio);

        other.setForeground(new java.awt.Color(255, 255, 255));
        other.setText("Other Genres");

        textS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textS.setForeground(new java.awt.Color(153, 153, 153));
        textS.setText("                                          Enter the User Name to Search "); // NOI18N
        textS.setToolTipText("");
        textS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSFocusLost(evt);
            }
        });
        textS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textSKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textS, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sPNo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sAge, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(classical)
                                    .addGap(18, 18, 18)
                                    .addComponent(country))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sMale)
                                        .addComponent(pop))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sFemale)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rock)
                                            .addGap(44, 44, 44)
                                            .addComponent(rb))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(93, 93, 93)
                                            .addComponent(hiphop)
                                            .addGap(18, 18, 18)
                                            .addComponent(other))))
                                .addComponent(jScrollPane2)
                                .addComponent(sCharge))
                            .addComponent(sUName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sFName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(164, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(textS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(sMale))
                    .addComponent(sFemale, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pop)
                    .addComponent(rock)
                    .addComponent(rb))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hiphop, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(other))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(classical)
                        .addComponent(country)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sFNameActionPerformed

    private void sChargeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sChargeKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_sChargeKeyTyped

    private void sPNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sPNoKeyTyped

        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_sPNoKeyTyped

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed

        dispose();
    }//GEN-LAST:event_cancel2ActionPerformed

    private void sSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSigninActionPerformed

        String sfname=sFName.getText();
        String slname=sLName.getText();
        String suname = sUName.getText();
        String spass = String.valueOf(sPWD.getPassword());
        String sphone = sPNo.getText();
        String semail = sEmail.getText();
        String saddress = sLocation.getText();
        String sage = sAge.getText();

        String sgender = "Male";
        if(sFemale.isSelected()){
            sgender = "Female";
        }

        String sgenre = " ";
        if(rock.isSelected()){
            sgenre= rock.getText()+" ";
        }
        if(classical.isSelected()){
            sgenre += classical.getText()+" ";
        }
        if(country.isSelected()){
            sgenre += country.getText()+" ";
        }
        if(rb.isSelected()){
            sgenre += rb.getText()+" ";
        }

        if(hiphop.isSelected()){
            sgenre += hiphop.getText()+" ";
        }
        if(pop.isSelected()){
            sgenre += pop.getText()+" ";
        }
        if(other.isSelected()){
            sgenre += other.getText()+" ";
        }

        String sbio = sBio.getText();
        String scharge = sCharge.getText();


            PreparedStatement ps;
            int p = JOptionPane.showConfirmDialog(null, "Are you sure to update this record ?","Update Recoed",JOptionPane.YES_NO_OPTION);
            
            if(p==0){
               
                try { 
                   String query = "UPDATE soloregister SET sFName=?,sLName=?,sUName=?,sPWD=?,sPNo=?,sEmail=?,sLocation=?,sAge=?,sGender=?,sGenre=?,sBio=?,sCharge=? WHERE sUName=?";
                    ps = DBconnection.getConnection().prepareStatement(query);

                    ps.setString(1, sfname);
                    ps.setString(2, slname);
                    ps.setString(3, suname);
                    ps.setString(4, spass);
                    ps.setString(5, sphone);
                    ps.setString(6, semail);
                    ps.setString(7, saddress);
                    ps.setString(8, sage);
                    ps.setString(9, sgender);
                    ps.setString(10, sgenre);
                    ps.setString(11, sbio);
                    ps.setString(12, scharge);
                    ps.setString(13, suname); 
                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(null,"Data Updated Successfully");
                    dispose();
                } catch (SQLException ex) {
                       JOptionPane.showMessageDialog(null,ex);
                }
            }
    }//GEN-LAST:event_sSigninActionPerformed

    private void textSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSFocusGained
        if(textS.getText().trim().equals("Enter the User Name to Search")  ){
            textS.setText("");
            textS.setForeground(new Color(153,153,153));
        }
        textS.setForeground(Color.BLACK);
    }//GEN-LAST:event_textSFocusGained

    private void textSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSFocusLost

        if(textS.getText().trim().equals(" ")  ){
            textS.setText("         Enter the User Name to Search ");
            sFName.setText(" ");
            sLName.setText(" ");
            sUName.setText(" ");
            sPWD.setText(" ");
            sPNo.setText(" ");
            sEmail.setText(" ");
            sLocation.setText(" ");
            sAge.setText(" ");
            sMale.setSelected(false);
            sFemale.setSelected(false);
            rb.setSelected(false);
            rock.setSelected(false);
            classical.setSelected(false);
            country.setSelected(false);
            pop.setSelected(false);
            hiphop.setSelected(false);
            other.setSelected(false);
            sBio.setText(" ");
            sCharge.setText(" ");
        }
    }//GEN-LAST:event_textSFocusLost

    private void textSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            PreparedStatement ps;
            ResultSet rs;
            try{

                ps = DBconnection.getConnection().prepareStatement("SELECT * FROM `soloregister` WHERE `sUName`=?");
                ps.setString(1,textS.getText());
                rs=ps.executeQuery();

                if(rs.next()){
                    sFName.setText(rs.getString(2));
                    sLName.setText(rs.getString(3));
                    sUName.setText(rs.getString(4));
                    sPWD.setText(rs.getString(5));
                    sPNo.setText(rs.getString(6));
                    sEmail.setText(rs.getString(7));
                    sLocation.setText(rs.getString(8));
                    sAge.setText(rs.getString(9));
                    
                    if(rs.getString(10).equals("Male")){
                        sMale.setSelected(true);
                        sFemale.setSelected(false);
                    }else if(rs.getString(10).equals("Female")){
                        sMale.setSelected(false);
                        sFemale.setSelected(true);
                    }
                    
                    if(rs.getString(11).equals("Pop")){
                        pop.setSelected(true);
                    }if(rs.getString(11).equals("Rock")){
                        rock.setSelected(true);
                    }if(rs.getString(11).equals("R&B")){
                        rb.setSelected(true);
                    }if(rs.getString(11).equals("Classical")){
                        classical.setSelected(true);
                    }if(rs.getString(11).equals("Country")){
                        country.setSelected(true);
                    }if(rs.getString(11).equals("Hip-hop")){
                        hiphop.setSelected(true);
                    }if(rs.getString(11).equals("Other Genres")){
                        other.setSelected(true);
                    }
                    
                    sBio.setText(rs.getString(12));
                    sCharge.setText(rs.getString(13));
                }
            } catch (SQLException ex) {
                Logger.getLogger(sUpdateProfile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_textSKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sUpdateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel2;
    private javax.swing.JCheckBox classical;
    private javax.swing.JCheckBox country;
    private javax.swing.JCheckBox hiphop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox other;
    private javax.swing.JCheckBox pop;
    private javax.swing.JCheckBox rb;
    private javax.swing.JCheckBox rock;
    private javax.swing.JTextField sAge;
    private javax.swing.JTextArea sBio;
    private javax.swing.JTextField sCharge;
    private javax.swing.JTextField sEmail;
    private javax.swing.JTextField sFName;
    private javax.swing.JRadioButton sFemale;
    private javax.swing.JTextField sLName;
    private javax.swing.JTextField sLocation;
    private javax.swing.JRadioButton sMale;
    private javax.swing.JTextField sPNo;
    private javax.swing.JPasswordField sPWD;
    private javax.swing.JButton sSignin;
    private javax.swing.JTextField sUName;
    private javax.swing.JTextField textS;
    // End of variables declaration//GEN-END:variables
}
